// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjiV41-rebE2aaGX1K8cK_HpqlTv1Zso',
    appId: '1:692061289127:web:9b197ca64e76d05abb7982',
    messagingSenderId: '692061289127',
    projectId: 'couple-app-6540a',
    authDomain: 'couple-app-6540a.firebaseapp.com',
    storageBucket: 'couple-app-6540a.firebasestorage.app',
    measurementId: 'G-4970N5R5DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKdBAtDJMvKT1HJ85F9ahCBs-usenGDPk',
    appId: '1:692061289127:android:73530285eb8bb25dbb7982',
    messagingSenderId: '692061289127',
    projectId: 'couple-app-6540a',
    storageBucket: 'couple-app-6540a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSewsKBhSzLHuOjkBrn28S74j5Ttiw0M',
    appId: '1:692061289127:ios:f84b0f6da5344c86bb7982',
    messagingSenderId: '692061289127',
    projectId: 'couple-app-6540a',
    storageBucket: 'couple-app-6540a.firebasestorage.app',
    iosBundleId: 'com.example.coupleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSewsKBhSzLHuOjkBrn28S74j5Ttiw0M',
    appId: '1:692061289127:ios:f84b0f6da5344c86bb7982',
    messagingSenderId: '692061289127',
    projectId: 'couple-app-6540a',
    storageBucket: 'couple-app-6540a.firebasestorage.app',
    iosBundleId: 'com.example.coupleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjiV41-rebE2aaGX1K8cK_HpqlTv1Zso',
    appId: '1:692061289127:web:be266797a1bcab0ebb7982',
    messagingSenderId: '692061289127',
    projectId: 'couple-app-6540a',
    authDomain: 'couple-app-6540a.firebaseapp.com',
    storageBucket: 'couple-app-6540a.firebasestorage.app',
    measurementId: 'G-CK8WFFHMT3',
  );
}
